version: "3.7"
services:
  server:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
