name: Continuous Integration

on:
  pull_request:
    branches:
      - "main"

jobs:
  lint_and_build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup-Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Lint
        uses: golangci/golangci-lint-action@v3

      - name: Build
        run: go build -v ./...
